[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
TESSDATA_PREFIX = "/usr/share/tesseract-ocr/5/tessdata"
